config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'mains#top'
  get 'form/:id' => 'mains#form'
  post 'form' => 'mains#create'


end

app/models/form.rb
class Form < ActiveRecord::Base
    belongs_to :user    
    mount_uploader :picture, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :image, ImageUploader
  has_many :forms

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         authentication_keys: [:username]


  def email_required?
    false
  end
  def email_changed?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :graduation, :college, :content, :image])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end

  
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController

    def top
        @form = Form.new
        @forms = Form.all.order('updated_at DESC')
    end

    def form
        @form = Form.find(params[:id])
    end

    def create
        @form = Form.new(form_params)
        @form.save
        redirect_to action: :top
    end

    def feed
        @form_feed = Form.all.order("id ASC")
    end

    def picture
        @content_pict = Form.select("picture")
    end

    def illust
        @content_illust = Form.select("illust")
    end

    def music
        @content_music = Form.select("music")
    end

    def movie
        @content_movie = Form.select("movie")
    end

    private
    def form_params
        #params.permit(:text, :picture, :illust)
        params.require(:form).permit(:text, :title, :picture, :category).merge(user_id: current_user.id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
    end

    def resource
        @resource ||= User.new
    end

    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shiroqma</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="header">
  <div class="icon">
    <%= image_tag("srQm-logo.png") %>
  </div>

  <div class="form">
    <div class="search">
      <input name="keyword" type="text" placeholder="タイトルで検索" class="search_form">
    </div>
    <div class="login">
    <% if user_signed_in? %>
      <%= link_to image_tag('logout.png'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= image_tag("login.png", class: 'loginButton') %>
    <% end %>
    </div>
  </div>

  
    <ul class="menu">
      <li class="ctg-icon"><%= link_to image_tag("home-Icon.png"), root_path %></li>
      <li class="ctg-icon"><%= image_tag("feed-Icon.png") %></li>
      <li class="ctg-icon"><%= image_tag("ctg-Icon.png") %>
        <ul class="category">
          <li class="picture ctg-icon2"><%= image_tag("pict-Icon.png") %></li>
          <li class="illust ctg-icon2"><%= image_tag("ilst-Icon.png") %></li>
          <li class="music ctg-icon2"><%= image_tag("music-Icon.png") %></li>
          <li class="movie ctg-icon2"><%= image_tag("movie-Icon.png") %></li>
        </ul>
      </li>
      <% if user_signed_in? %>
        <li class="ctg-icon"><%= image_tag("mypg-Icon.png") %></li>
      <% else %>
        <li class="ctg-icon"><%= image_tag('signup-Icon.png', class: 'signUpButton' ) %></li>
      <% end %>
    </ul>

    <div id="loginModalWrapper">
      <div class="loginModal">
        <div class="loginForm">
          <div class="title">
          log in
          </div>
          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
            <div class="userName">
              <%= f.text_field :username, {class: 'userForm', placeholder: 'username'} %>
            </div>
            <div class="password">
              <%= f.password_field :password, {autocomplete: "off", class: 'passForm', placeholder: 'password'} %>
            </div>
            <%= f.submit 'login',{style: 'display:none'} %>
          <% end %>
        </div>
      </div>
    </div>

    <%#サインアップモーダル%>
    <div id="signUpModalWrapper">
      <div class="signUpModal">
        <div class="signUpForm">
          <div class="title">
            Sign Up
          </div>
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
          <div class="image">
            <%= f.label :image, 'Upload Image', {class: 'imageLabel'} %>
            <%= f.file_field :image, {style: 'display:none'} %>
          </div>
          <div class="userName">
            <%= f.text_field :username, {class: 'userForm', placeholder: 'username'} %>
          </div>
          <div class="password">
            <%= f.password_field :password, {autocomplete: "off", placeholder: 'password', class: 'passForm'} %>
          </div>
          <div class="graduation">
            <%= f.text_field :graduation, {class: 'gradForm', placeholder: '　卒業'} %>
          </div>
          <div class="college">
            <%= f.text_field :college, {class: 'colForm', placeholder: '　学校'} %>
          </div>
          <div class="content">
            <%= f.text_area :content, {class: 'conForm', placeholder: 'and more...'} %>
          </div>
          <%= f.submit :class => 'submit', :value => '' %>
          <% end %>
        </div>
      </div>
    </div>
  
</div>

<%= yield %>


 

</body>
</html>

app/views/mains/form.html.erb
<p class="line"></p>


<div class="detail">
    <div class="title"><%= @form.title %></div>

    <div class="user">
    　<%= image_tag(@form.user.image.url, class: 'userIcon')%>
      <a class="userName"><%= @form.user.username %></a> 
      <div class="time">2016 / 05 / 28 13:25</div>
    </div>

    <div class="content">
        <%= image_tag(@form.picture, class: 'image') %>
        <div class="likeText">like: 31</div>
        <div class="likeIcon">
            <%= image_tag('like-Icon.png') %>
        </div>
        <div class="tag">
            #Phototo  #コントラスト強め  #地元で撮った
        </div>
        <div class="text">
            <%= @form.text %>
        </div>
    </div>
</div>


<p class="line"></p>

<div class="top">
        <%= link_to 'topへ', root_path, class: 'topLink' %>
</div>

app/views/mains/top.html.erb
<div class="formButton">
    <%= image_tag('formButton.png') %>
</div>


<div id="formModalWrapper">
    <div class="formModal">
        <div class="uploadForm">
            <div class="title">
            Upload
            </div>
            <%= form_for @form,:url => {:action => 'create'} do |f| %>
                <div class='image'>
                    <%= f.label :picture, 'Upload Image', {class: 'imageLabel'} %>
                    <%= f.file_field :picture, {style: 'display:none'} %>
                </div>
                
                <%#ここは後でタイトルデータベース作って修正%>
                <div>
                    <%= f.text_field :title, {class: 'formTitle', placeholder: 'title'} %>
                </div>
                <%#同じくデータベース追加して修正%>
                <div class="category">
                    <label class="categoryTitle">select category</label>
                   <div class="radioButton">
                        image<%= f.radio_button 'category', 'image'%>
                        illust<%= f.radio_button 'category', 'illust'%>
                        music<%= f.radio_button 'category', 'music'%>
                        movie<%= f.radio_button 'category', 'movie'%>
                   </div>
                </div>
                <div class="belongTag">
                    <div class="belongTagTitle">
                        所属tag
                    </div>
                </div>
                <div class="tag">
                    <div class="tagTitle">
                        tag
                    </div>
                </div>
                <div class="details"> 
                    <%= f.text_area :text, {class: 'detail', placeholder: 'caption or detail'} %>
                </div>

                <div>
                <%= f.submit :class => 'submit', :value => '' %>
                </div>
            <% end %>
        </div>
    </div>
</div>

<div class="contents">
    <% @forms.each do |form| %>
    <div class="content">
        <%= link_to image_tag(form.picture.url, :class => "image-size"), "/form/#{form.id}", method: :get %>
        <div class="like">
            <%= image_tag('like-Icon.png') %>
            
        </div>
        <div class="user">
            <%= image_tag(form.user.image.url, class: 'userIcon') %>
            <%= form.user.username %>
        </div>
    </div>
    <% end %>




    <div class="content">
        
    </div>
    <div class="content">
        
    </div>
    <div class="content">
        
    </div>
    <div class="content">
        
    </div>
    <div class="content">
        
    </div>
</div>